spring:
  application:
    name: users-api

  r2dbc:
    url: r2dbc:oracle://localhost:1521/FREEPDB1
    username: app_user
    password: UsersApi!

  flyway:
    enabled: true
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    user: app_user
    password: UsersApi!
    schemas: APP_USER
    locations: classpath:db/migration

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.spi: INFO
    org.flywaydb: INFO
    org.springframework.boot.autoconfigure: INFO