CREATE TABLE USERS (
   ID          VARCHAR2(36)    NOT NULL,
   NAME        VARCHAR2(255)   NOT NULL,
   NICK        VARCHAR2(100),
   BIRTH_DATE  DATE            NOT NULL,
   CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

CREATE TABLE STACKS (
    ID           VARCHAR2(36)  NOT NULL,
    USER_ID      VARCHAR2(36)  NOT NULL,
    NAME         VARCHAR2(100) NOT NULL,
    SKILL_LEVEL  NUMBER(10)    NOT NULL,
    CONSTRAINT PK_STACKS PRIMARY KEY (ID),
    CONSTRAINT FK_STACKS_USERS
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID)
                ON DELETE CASCADE
);